事業をエンジニアリングしよう ②実装
shohei0808/mokumoku pull request #2
Opened 2023-01-31 20:48 UTC by shohei0808

<img width="889" alt="dcf55846c4c9b87a0d6eb8172ca72860" src="https://user-images.githubusercontent.com/106419302/215879154-adde7db9-7f4a-4757-b8bc-cecff3c42e0d.png">

卒業試験の事業をエンジニアリングしよう 実装編です。レビューよろしくお願いいたします。

2023-02-02 05:06 UTC, Tsuchiya2 reviewed
コメントしました！

2023-02-02 05:06 UTC, Tsuchiya2 commented on app/decorators/relationship_decorator.rb
> +class RelationshipDecorator < Draper::Decorator
使っていないファイルのようですね。削除しておきましょう

2023-02-02 05:06 UTC, Tsuchiya2 commented on config/routes.rb
> +  resources :users do
この記載だと7つのアクションのルーティングが生成されてしまいますね。使っていないルーティングがあると予期せぬリクエストを受け取ってしまうので修正しましょう。

2023-02-02 05:06 UTC, Tsuchiya2 commented on spec/decorators/relationship_decorator_spec.rb
> +require 'rails_helper'
使っていないファイルですかね？

2023-02-02 10:03 UTC, shohei0808 commented
いらないファイルは消してコードは修正しました。
確認よろしくお願いいたします。

2023-02-02 12:17 UTC, busitora requested changes
コメントいたしました！

2023-02-02 12:17 UTC, busitora commented on app/models/user.rb
> +    relationships.find_by(followed_id: user_id).destroy
`relationships.find_by(followed_id: user_id)`

が nil になった場合、 destroy するとどんなエラーになるでしょうか
実際に試して見て、必要であれば修正おねがいします。

2023-02-02 12:17 UTC, busitora commented on app/views/users/show.html.erb
> +        <% unless @user == current_user %>
@user == current_user
を model method で定義し、model spec もできれば書いてみてください。

2023-02-02 12:17 UTC, busitora commented on spec/factories/relationships.rb
> +    follower_id { 1 }
マジックナンバーの記載はやめましょう！
修正してください！

2023-02-02 12:17 UTC, busitora commented on spec/requests/relationships_spec.rb
> +RSpec.describe "Relationships", type: :request do
不要なSpecファイルは削除おねがいします！

2023-02-03 05:10 UTC, shohei0808 commented
@user == current_userを model method で定義するの部分で詰まっています。ここでの質問は可能なのでしょうか？
可能ならヒントを頂けたら幸いです。
モデルで
def current_user?(user)
  user == current_user
end
を定義した後のエラー文を載せておきます。
他のファイルは自分なりに修正しました。合わせてご確認よろしくお願い致します。

<img width="1677" alt="b8b8a165a821da4733b531d0ea1f148c" src="https://user-images.githubusercontent.com/106419302/216517528-0a5e622b-aacd-4601-be1a-f7485615b065.png">

2023-02-03 12:07 UTC, takyyk commented
@shohei0808 
viewにcurrent_user?()メソッドを単体でおいても、どこで定義されているメソッドかわからないので
呼び出せないですね。
Userモデルで定義しているメソッドを使いたいのでcurrent_userが使えることを利用して、
current_user.メソッド名のような形で呼び出すのはどうでしょうか。

```
def following?(user)
    followings.include?(user)
  end
```
で定義して、```current_user.following?(引数名)```のような形で実装しているのを参考に、

current_user.メソッド名でtrue or false を返すようなイメージでメソッドを定義するとよいかと思います。

2023-02-03 21:28 UTC, shohei0808 commented
かなりの時間を費やしたのですが未だ詰まっています。（色々ググってメソッドたくさん試しました）
例えば
def user_login?(user)
    user.presence?(user)
end
みたいなメソッドをモデルで定義してビューで<% unless current_user.user_login? %>みたいな感じでしょうか？
そもそも真偽判定のメソッドの作り方で悩んでいます。(presentなのかblankなのかpresenceなのかなどなど)
もしよろしかったらもう少しヒントを頂けたら幸いです。

2023-02-04 03:27 UTC, masa-oh commented
真偽値を返すメソッドだからと言って難しく考えず、元々viewに書いていたコードを抽象化してmodelに定義し直す作業と考えればいいですよ。
元は`@user == current_user`を比較していましたよね。`==`で比較するとtrue or falseが返ってくるので、この結果を返すことが真偽判定と言えますね。

もう一つヒントをお伝えすると、インスタンスメソッドを呼び出す際、レシーバ（メソッドを呼び出しているオブジェクト自身）は`self`で取得することができます。
今回ユーザーモデルに定義するのは、「レシーバ自身と、引数で渡したuserが同一かどうか」を判定するメソッドだと考えたら、答えが見えてきませんか？

それと、レビューの修正に関してですが、指摘事項の各コメントに返信する形で、「 3640752 で対応しました。」などのように、コミットID付きでコメントをお願いします！（できればコミットも分割してあるとより見やすいですが、今回はそのままで大丈夫です。）
どの指摘事項に対応したかを確認する手間がお互いに省けますので、そのようにしていただけるとありがたいです！

2023-02-04 05:18 UTC, shohei0808 commented
本当に丁寧な対応ありがとうございます。[c54ecba]と[dd4e261]で対応しました。
どうにかモデルに定義できました。レビューお願いします。
あと度々の質問申し訳ないのですが謎のテストエラーが出ました。
今まで出たことなかったのに急にです。ちなみに機能は無事動いています。どうすれば良いのか困ったいます。
お力お借りしたいです。よろしくお願いします。

![6443da10927f120d5f761bb0b5cf8617](https://user-images.githubusercontent.com/106419302/216750106-cc3bda4e-02eb-4e11-9941-64b83c176ae6.jpg)

2023-02-04 05:38 UTC, shohei0808 commented
すいません。テストエラー無事解決しました。
改めてレビューお願いします。
<img width="885" alt="e38e6bc7ad5fde7dec5ecebb3a16c437" src="https://user-images.githubusercontent.com/106419302/216750847-ecd43978-94a6-42a6-a5d3-96027d45f4cd.png">

2023-02-04 05:48 UTC, masa-oh commented
対応ありがとうございます。
変更事項が多いので、「[コミットID]で対応しました。」というコメントは、土屋さんとブシトラさんから指摘されていた各コメントのツリーに返信する形でお願いできますでしょうか。

レビュイーにとっては、どの指摘事項に対応済みかを確認しながらコメントすることで、対応漏れがないかセルフレビューできるというメリットがあります。
レビュアーにとっても、同じく対応漏れがないか一目で確認できるので、お互いの労力を削減するためにコメントしていただけると、とても助かります！

2023-02-04 05:50 UTC, shohei0808 commented
かしこまりました。今回でプルリクエストの効率のいいレビューの流れ勉強になりました。
ありがとうございました。

2023-02-04 05:54 UTC, shohei0808 commented on config/routes.rb
> +  resources :users do
[c9a5270]　で対応しました。確認よろしくお願い致します。

2023-02-04 05:54 UTC, shohei0808 commented on spec/decorators/relationship_decorator_spec.rb
> +require 'rails_helper'
[c9a5270]　で対応しました。確認よろしくお願い致します。

2023-02-04 05:54 UTC, shohei0808 commented on app/decorators/relationship_decorator.rb
> +class RelationshipDecorator < Draper::Decorator
[c9a5270]　で対応しました。確認よろしくお願い致します。

2023-02-04 05:56 UTC, shohei0808 commented on spec/requests/relationships_spec.rb
> +RSpec.describe "Relationships", type: :request do
[3640752]で対応しました。確認よろしくお願い致します。

2023-02-04 05:58 UTC, shohei0808 commented on spec/factories/relationships.rb
> +    follower_id { 1 }
[3640752]で対応しました。確認よろしくお願い致します。

2023-02-04 06:00 UTC, shohei0808 commented on app/views/users/show.html.erb
> +        <% unless @user == current_user %>
[c54ecba]と[dd4e261]で対応しました。確認よろしくお願い致します。

2023-02-04 06:01 UTC, masa-oh commented on app/models/user.rb
> +    relationships.find_by(followed_id: user_id).destroy
こちら対応をお願いします。

2023-02-04 06:01 UTC, masa-oh commented on app/views/users/show.html.erb
> +        <% unless @user == current_user %>
こちら c54ecba と dd4e261 で修正を確認しました。
この変更は同じ点に関する修正なので、コミットはまとめた方が良いですね。
また、コミットメッセージも毎回同じではなく、「refactor: viewの処理をmodelに切り出した」など、なんでもいいので変更内容が分かるようなメッセージを書けると良いですね。

2023-02-04 06:01 UTC, masa-oh commented on spec/factories/relationships.rb
> +    follower_id { 1 }
記述を丸ごと消すのではなく、同じ結果になる処理で、マジックナンバーを使わないように修正できますか？
マジックナンバーがわからなかったら、調べてみてください。

2023-02-04 06:01 UTC, masa-oh commented on spec/requests/relationships_spec.rb
> +RSpec.describe "Relationships", type: :request do
こちらは 3640752 で修正されていることを確認しました。

2023-02-04 06:04 UTC, masa-oh commented on spec/requests/relationships_spec.rb
> +RSpec.describe "Relationships", type: :request do
確認しました！

2023-02-04 06:05 UTC, shohei0808 commented on app/views/users/show.html.erb
> +        <% unless @user == current_user %>
すいません。今後そこも気をつけます。

2023-02-04 06:05 UTC, masa-oh commented
ツリーにコメントしました！
2点修正が残っているので、引き続き対応をお願いします。

2023-02-04 06:10 UTC, shohei0808 commented on app/models/user.rb
> +    relationships.find_by(followed_id: user_id).destroy
relationships.find_by(followed_id: nil).destroyにすると言うことでしょうか？
試してみたら下記のようなエラーが出ました。これはnilでもdestroyできるようにすると言うことでしょうか？
もし良ければ少しお力借りたいです。

<img width="1677" alt="b8b8a165a821da4733b531d0ea1f148c" src="https://user-images.githubusercontent.com/106419302/216752037-2e4f2ff6-ae59-426d-acfa-adfafc2073a4.png">

2023-02-04 06:25 UTC, shohei0808 commented on spec/factories/relationships.rb
> +    follower_id { 1 }
[ea12460]で対応しました。ご確認よろしくお願いします。

2023-02-04 07:37 UTC, masa-oh commented on app/models/user.rb
> +    relationships.find_by(followed_id: user_id).destroy
`relationships.find_by(followed_id: user_id).destroy`というコードは、`relationships.find_by(followed_id: user_id)`で見つかったRelationshipに対してdestroyをしますよね。
ここでもし無効なuser_idが指定されるなどしてRelationshipが見つからなかった場合、`nil.destroy`のように呼び出そうとしてしまい、エラーになりますね。
このような場合、やり方は複数ありますが、ぼっち演算子を使うのが最もシンプルな解決策かと思います。

2023-02-04 07:39 UTC, masa-oh commented on spec/factories/relationships.rb
> +    follower_id { 1 }
user_idはどこにも定義されていないので、これだとエラーになってしまうかと思います。
`association`という記述を使って書き直してみてください。
参考：https://qiita.com/Ryoga_aoym/items/741c57e266a9d811a2d4

2023-02-04 07:40 UTC, masa-oh commented
コメントしましたので、ご確認お願いします！

2023-02-04 07:55 UTC, shohei0808 commented on app/models/user.rb
> +    relationships.find_by(followed_id: user_id).destroy
[3c5c71b]で対応しました。ご確認お願いします。

2023-02-04 07:56 UTC, shohei0808 commented on spec/factories/relationships.rb
> +    follower_id { 1 }
[3c5c71b]で対応しました。ご確認お願いします。

2023-02-04 08:07 UTC, masa-oh commented on spec/factories/relationships.rb
> +    follower_id { 1 }
上に書いた通り、user_idはどこにも定義されていないので、これだとエラーになってしまうかと思います。
`follower_id { user_id }` などの記載は削除しましょう。

ここで作りたい関連データはfollower, followedだと思いますので、こちらの記載に直してください。
```
association :follower
association :followed
```

2023-02-04 08:15 UTC, shohei0808 commented on spec/factories/relationships.rb
> +    follower_id { 1 }
[45900cf]で対応しました。確認よろしくお願い致します。

2023-02-04 08:22 UTC, masa-oh commented on spec/factories/relationships.rb
> +    follower_id { 1 }
`:follower`はひとまとまりでシンボルなので、コロンとfollowerの間にスペースは不要ですね。
FactoryBotのassociationにシンボルを渡すと、同名のアソシエーションがRelationモデルで定義されているかを探しに行きます。

2023-02-04 08:22 UTC, masa-oh commented
まだ直っていないので、再度ご確認ください。

2023-02-04 08:27 UTC, shohei0808 commented on spec/factories/relationships.rb
> +    follower_id { 1 }
何度も初歩的なことですいませんでした😭
[fb5370c]で修正しました。

2023-02-04 08:31 UTC, masa-oh commented
対応お疲れ様でした！LGTMです！

2023-02-04 08:34 UTC, shohei0808 commented
本当にありがとうございました。そして何度もすいませんでした。
クリアできたのは丁寧な対応とヒントのおかげです。ほんまありがとうございました。

2023-02-04 08:54 UTC, merged